# Generated by Django 2.2.2 on 2019-06-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='user_id',
            new_name='user',
        ),
    ]
